name: Plugin Test
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run ut
  func-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - name: Run kong on docker
        shell: bash
        env:
          UT_POSTGRES_VER: 11.14
        run: docker-compose up -d
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run ft
