name: Plugin Test
on: [push]
jobs:
  # TODO Uncomment when adding unit test file
  # unit-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 14.16.0
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run test
  #       run: npm run ut
  func-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - uses: kong/setup-deck@v1
        with:
          deck-version: 1.7.0
      - name: Run kong on docker
        run: npm run up
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run ft
